[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"  # Change to "dark" for dark mode
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"

[client]
showErrorDetails = false  # Hide detailed error messages in production
toolbarMode = "minimal"  # Remove the "Run" button in production

[logger]
level = "info"